version: '3.8'

services:
  postgres:
    build: 
      context: ./database/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./database/admin/.env
  
  inventario:
    build: 
      context: ./src/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - 5000:5000
      - 5001:5001
    env_file:
      - ./src/.env